### ISSUE TITLE
開発環境を整備する

### ISSUE THREAD

**Issue by SasakiPeter** [SasakiPeter/56gen#26]
dockerで作ってあるローカルの開発環境が動作しない。
postgresの仕様が変更されているのも一つの原因と思われる。

そもそもrequirements.txtを読み込んでいない設計も問題なので、その辺から作り直す。

**Comment by kudoas** [comment]
フロントとバックエンドはモノレポが良さそう！

**Comment by SasakiPeter** [comment]
#27

**Comment by SasakiPeter** [comment]
このままモノレポの予定！
とりあえずローカルで動くようになったので確認してください。

**Comment by kudoas** [comment]
とりあえずバックエンドだけ動くようにした感じですかね。
